on:
  push:
    branches: ["*"]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run: |
          printenv

  token:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - run: |
          printenv
